excluded:
  - Carthage
  - Package.swift
  - Consumption-Tests/*/Carthage
  - Consumption-Tests/*/Pods

opt_in_rules:
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces

identifier_name:
  excluded:
  - id
  - ex
  - to
  - ws

# This generates a compiler error if more than this many SwiftLint warnings are present
# (This threshold can become more restrictive as remaining warnings are resolved via refactoring)
warning_threshold: 13